### PR TITLE
add Airflow doc chinese and update info

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Add Airflow documentation in chinese
* Remove incubating label
* Update Airflow release to 1.10.2

### CODE REVIEW

**Comment by feng-tao** [comment]
very cool! thanks @zhongjiajie

**Comment by feng-tao** [comment]
cc @jghoman

**Comment by zhongjiajie** [comment]
@feng-tao Thanks, I just find the CN doc today in github **Discover repositories** list.

**Comment by jghoman** [comment]
Looks good.  Thanks!

**Comment by zhongjiajie** [comment]
@jghoman You are welcome.

**Pull request merged**
