### PR TITLE
Add Airflow Repository Template

### PR DESCRIPTION
**Pull request by soggycactus**
I've now worked on 4 different Airflow installations in my data engineering career, and I keep a template of a boilerplate codebase for developing locally with Airflow - the template is used to kickstart an Airflow codebase that is then deployed to where-ever Airflow lives (EC2, K8s, Astronomer, Composer, etc.)

I figured I'd share my template as I've gotten good feedback about it! You can literally clone the template and run `make start-airflow` to get Airflow up and running locally. The repo also comes with linting (pylint and black) and unit testing for valid DAGs and plugins already baked in. Simply add your DAGs and additional pip dependencies, some CI jobs to deploy and you're done!

EDIT: I should post the actual repo so you can review and decide if it's worthy: https://github.com/soggycactus/airflow-repo-template

### CODE REVIEW

**Comment by potiuk** [comment]
Out of curiosity @soggycactus 

Do you know about Breeze ? https://github.com/apache/airflow/blob/master/BREEZE.rst ? (see the movie which is embedded there as well). It is part of the airflow repo and you can run:

`./breeze start-airflow`

And you get hackable Airflow up and running with all the bells and whistles you might imagine (including choosing python versions, database backend, choosing whether you want to add example dags or not, you have immediate access to gcloud/aws/azure command line tools, all the integrations supported by Airflow if you need them (many of those) and a number of other helpful commands:

`./breeze --help` to see the options you might want to use.

It is based on docker-compose, and uses the same images as those used during the CI tests for Airlfow, so no matter what OS/libraries you have installed in your host, you will always get a consistent (and automatically refreshing with the latest changes in Airflow) environment.

I was wondering - there are a few things that might be useful to have in breeze - from your description - liniting and unit testing for dags, so maybe instead of introducing yet-another-environment for Airflow, you could contribute those features to Breeze.

**Review by jghoman — APPROVED** [review]

**Comment by jghoman** [comment]
Thanks, @soggycactus

**Comment by soggycactus** [comment]
> Out of curiosity @soggycactus
> 
> Do you know about Breeze ? https://github.com/apache/airflow/blob/master/BREEZE.rst ? (see the movie which is embedded there as well). It is part of the airflow repo and you can run:
> 
> `./breeze start-airflow`
> 
> And you get hackable Airflow up and running with all the bells and whistles you might imagine (including choosing python versions, database backend, choosing whether you want to add example dags or not, you have immediate access to gcloud/aws/azure command line tools, all the integrations supported by Airflow if you need them (many of those) and a number of other helpful commands:
> 
> `./breeze --help` to see the options you might want to use.
> 
> It is based on docker-compose, and uses the same images as those used during the CI tests for Airlfow, so no matter what OS/libraries you have installed in your host, you will always get a consistent (and automatically refreshing with the latest changes in Airflow) environment.
> 
> I was wondering - there are a few things that might be useful to have in breeze - from your description - liniting and unit testing for dags, so maybe instead of introducing yet-another-environment for Airflow, you could contribute those features to Breeze.

@potiuk I had not heard of this!! You make some good points, I think it's a great idea to add these features to Breeze - could I add you as a reviewer if I throw up a PR?

**Comment by potiuk** [comment]
Absolutely !

**Pull request merged**
