### PR TITLE
Added refreshed Breeze video

### PR DESCRIPTION
**Pull request by potiuk**

### CODE REVIEW

**Comment by potiuk** [comment]
@jghoman -> rebased the new Breeze video (using it in workshops day after tomorrow :)

**Comment by potiuk** [comment]
Yeah. It was a diferrent presentation but yeah. It's outdated now, so let's remove it

**Comment by potiuk** [comment]
Done !

**Comment by jghoman** [comment]
Thanks, Jarek!

**Comment by mik-laj** [comment]
Thanks, Jakob!

**Pull request merged**
