### PR TITLE
Add Data Testing With Airflow repo and update URL

### PR DESCRIPTION
**Pull request by tedmiston**

### CODE REVIEW

**Comment by tedmiston** [comment]
Hey @jghoman can you please take a look at this small PR when you get a chance and see if it looks good to merge?

**Comment by jghoman** [comment]
Rather than just a naked link in the text, can we add a description of what's being linked to? That's been the pattern thus far in the document.

**Comment by tedmiston** [comment]
@jghoman Thank you - updated now per your feedback.

**Comment by jghoman** [comment]
Looks good.  Thanks.

**Pull request merged**
