### PR TITLE
removed puckel and fixed version

### PR DESCRIPTION
**Pull request by yene**
airflow now has its own official dockerimage

### CODE REVIEW

**Comment by jghoman** [comment]
Hey @yene.  Thanks for this.  So, Puckel appears to still be updating their [images](https://github.com/puckel/docker-airflow/commits/master) and Airflow's official images are a built buried in a [separate file](https://github.com/apache/airflo), rather than the main readme.  What if we leave Puckel's link, as it's still active, and add a new line in the top section pointing to the images.md in the official repo?  Thoughts?

**Comment by potiuk** [comment]
We can still leave puckel as "legacy" way of running Airflow - many people are still using it and likely the new prod image has still few iterations to get rock solid.


BTW. We have a section about building images in main readme :) 
 https://github.com/apache/airflow/blob/master/README.md#building-customized-production-images

**Comment by jghoman** [comment]
Yeah, but it's titled "*Building* customized images" but (that section at least) is talking about *pulling* images.  May be worth a PR to add an explicit sections "Using official Docker images" or something...

**Comment by potiuk** [comment]
Right!

**Comment by potiuk** [comment]
Fixed @jghoman in https://github.com/apache/airflow/pull/9925

**Pull request closed without merging**
